INSERT INTO CIDADE (ID, NOME, ESTADO) VALUES (cidade_seq.NEXTVAL, 'Recife', 'PE');
INSERT INTO CIDADE (ID, NOME, ESTADO) VALUES (999, 'São Paulo', 'SP');
INSERT INTO CLIENTE (ID, NOME, SEXO, NASCIMENTO, IDADE, CIDADE_ID) VALUES (cliente_seq.NEXTVAL, 'Ícaro', 'M', TO_DATE('29/04/1992', 'DD/MM/YYYY'), 27, 1);